name: Upload Artifact

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Package artifact
        run: mvn package -P fat-jar pl mybatis-generator-plugins-core

      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.upload_url }}
          asset_path: mybatis-generator-plugins-core/target/mybatis-generator-plugins-core.jar
          asset_name: mybatis-generator-plugins-core.jar
          asset_content_type: application/zip

